### ISSUE TITLE
Add WSL supporting

### ISSUE THREAD

**Issue by quantum3k** [timo-reymann/intellij-mjml-support#123]
When in IDE i using WSL. In preview always shows  _**Failed to render mjml using helper script**_  because all excutables developing application (nodejs and etc) placed in WSL subsystem, and i think renderers cannot executes.
I suggest add to plugin supporting WSL2 features in IDE.

**Comment by timo-reymann** [comment]
Hi @quantum3k,

i will have to evaluate if this works right away with some minor changes. 
Currently I dont have a Windows installation with IntelliJ to test it, so i first have to setup everything for that.

If it requires huge effort and might break in the future i wont implement this since maintaining a Windows setup just for this is not reasonable for me.

Kind regards
Timo

**Comment by timo-reymann** [comment]
Heya,

i had a look at it. Its just to much work to support and maintain WSL support.

So i will close this ticket.

Kind regards
Timo
