### ISSUE TITLE
Cannot render MJML preview when using WSL Node

### ISSUE THREAD

**Issue by Ririshi** [timo-reymann/intellij-mjml-support#14]
When using the plugin with a WSL setup, it tries to find `node` using the WSL path, but I think it is trying to find it in the Windows filesystem, which obviously doesn't exist. I get the following error:
```
C:\Users\Ririshi\AppData\Roaming\JetBrains\PhpStorm2021.1\plugins\mjml-support\renderer\index.js: 1: /home/ririshi/.nvm/versions/node/v14.7.0/bin/node: not found
```

I verified that the executable exists inside WSL:

```
❯ which node
/home/ririshi/.nvm/versions/node/v14.17.0/bin/node
```

I suppose there are two ways to fix this. Either create a setting for a Windows node executable path, or detect that the user is using a WSL setup and run the WSL node executable. I personally thing the latter is a better option, since it does not require an additional node installation on the Windows side. I can imagine the user does not have one if they are developing inside WSL.

**Comment by timo-reymann** [comment]
Hello @Ririshi,

thanks for your report.

Have you set up the node interpreter from wsl? https://www.jetbrains.com/help/webstorm/node-js-interpreters.html

I use the regular node.js settings for your current project in the preview. So if it is set up correctly it should work out of the box.

**Comment by Ririshi** [comment]
I have set up a Node interpreter on my WSL. It does pick up the right path (the one mentioned in the OP), but it says that the node executable just doesn't exist, even though `which node` confirms its existence.

**Comment by timo-reymann** [comment]
So i set up a fresh wsl with Ubuntu 20 now and it seems the way IntelliJ handles Node.JS integration simply doesnt work with my approach.

In my case when calling a node.js script with an wsl interpreter the cli looks like this:

``C:\Windows\system32\wsl.exe --distribution Ubuntu-20.04 --exec /bin/sh -c "cd '/mnt/c/Users/Timo Reymann/IdeaProjects/untitled' && /usr/bin/node '/mnt/c/Users/Timo Reymann/IdeaProjects/untitled/index.js'"``

I use the stdin to pass the current editor buffer, that simply doesnt work with wsl because the buffer is not redirected to stdin as it would on MacOS or linux. 

So the only way to make it work in this case is to use a natively installed Node
