### ISSUE TITLE
Handlebars support

### ISSUE THREAD

**Issue by Alex237** [timo-reymann/intellij-mjml-support#45]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am using Handlebars to inject data in my template. i wanted to keep `.mjml` and use this extension support, without renaming my file with `.hbs` exentension
Is it possible to add in the setting, the template's engine choice, like mustache, handlebars, and other ? and have their synthax highligting

**Comment by timo-reymann** [comment]
Related to #11, as stated here you can add the hbs extension as mjml or some custom extension like .mjml.hbs.

If you have a proposal for a preferred pattern, please feel free to add it as a comment.

Currently there is no support for template languages, due to the implementation of the plugin. And for now it would be too much effort.
